[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/treatments/*"
  to = "/treatments/:splat"
  status = 200

[[redirects]]
  from = "/hospitals/*"
  to = "/hospitals/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
